// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// MANUAL CONFIGURATION TEMPLATE (Sensitive data removed)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REDACTED***',
    appId: '***REDACTED***',
    messagingSenderId: '***REDACTED***',
    projectId: '***REDACTED***',
    authDomain: '***REDACTED***',
    storageBucket: '***REDACTED***',
    measurementId: '***REDACTED***',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REDACTED***',
    appId: '***REDACTED***',
    messagingSenderId: '***REDACTED***',
    projectId: '***REDACTED***',
    storageBucket: '***REDACTED***',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REDACTED***',
    appId: '***REDACTED***',
    messagingSenderId: '***REDACTED***',
    projectId: '***REDACTED***',
    storageBucket: '***REDACTED***',
    iosBundleId: '***REDACTED***',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REDACTED***',
    appId: '***REDACTED***',
    messagingSenderId: '***REDACTED***',
    projectId: '***REDACTED***',
    storageBucket: '***REDACTED***',
    iosBundleId: '***REDACTED***',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REDACTED***',
    appId: '***REDACTED***',
    messagingSenderId: '***REDACTED***',
    projectId: '***REDACTED***',
    authDomain: '***REDACTED***',
    storageBucket: '***REDACTED***',
    measurementId: '***REDACTED***',
  );
}
